### ISSUE TITLE
Improve autoconfigure module

### ISSUE THREAD

**Issue by eddumelendez** [openzipkin-contrib/zipkin-storage-forwarder#1] opened 2019-06-25 06:48 UTC
The current `spring-boot` support can be improved. This is regarding the structure of `autoconfigure` module.

* Make `http` and `kafka` packages in `autoconfigure` instead of modules
* Provide auto-configuration providing starters which will provide the right dependencies and will enable `http` or `kafka`

Also, this new approach can take advantage of adding `additional-spring-configuration-metadata.json` file for `zipkin.storage.type` which will provide IDE support for developers to choose between `http-forwarder` or `kafka-forwarder`.

**Comment by eddumelendez** [comment] 2019-06-25 06:48
I can work on it :)

**Comment by jeqo** [comment] 2019-06-26 12:38
Sounds great!
Fixed by #2 

Thanks Eddu!

**Comment by eddumelendez** [comment] 2019-06-26 15:09
Can we reopen it? This is not solved by #2

**Comment by jeqo** [comment] 2019-06-26 15:21
Sorry I rushed to merge it, feel free to open a new PR to complete the changes

**Comment by codefromthecrypt** [comment] 2020-11-20 07:09
zipkin internally uses a different loading mechanism which is faster and less problematic than spring boot as they often change loading things between releases. it is currently in #11

**Comment by codefromthecrypt** [comment] 2024-01-15 07:09
I think there is nothing to do here, because the module system is being used as intended and matches exactly zipkin-aws zipkin-gcp and zipkin-storage-kafka

**Closed as completed by codefromthecrypt** 2024-01-15 07:09 UTC
